<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260907125307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pesee_paquet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, poids DOUBLE PRECISION DEFAULT NULL, observations TEXT DEFAULT NULL, ligne_dechargement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_592BA4A9AB8100B0 ON pesee_paquet (ligne_dechargement_id)');
        $this->addSql('ALTER TABLE pesee_paquet ADD CONSTRAINT FK_592BA4A9AB8100B0 FOREIGN KEY (ligne_dechargement_id) REFERENCES ligne_dechargement (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pesee_paquet DROP CONSTRAINT FK_592BA4A9AB8100B0');
        $this->addSql('DROP TABLE pesee_paquet');
    }
}
