<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260219092803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE planning (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_planning DATE NOT NULL, categorie VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE planning_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, heure_mise_adisposition TIME(0) WITHOUT TIME ZONE DEFAULT NULL, avancement BOOLEAN NOT NULL, avancement_code VARCHAR(10) DEFAULT NULL, observations TEXT DEFAULT NULL, planning_id INT NOT NULL, bon_travail_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C65C611C3D865311 ON planning_ligne (planning_id)');
        $this->addSql('CREATE INDEX IDX_C65C611CB2DABD03 ON planning_ligne (bon_travail_id)');
        $this->addSql('ALTER TABLE planning_ligne ADD CONSTRAINT FK_C65C611C3D865311 FOREIGN KEY (planning_id) REFERENCES planning (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_ligne ADD CONSTRAINT FK_C65C611CB2DABD03 FOREIGN KEY (bon_travail_id) REFERENCES bon_travail (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE planning_ligne DROP CONSTRAINT FK_C65C611C3D865311');
        $this->addSql('ALTER TABLE planning_ligne DROP CONSTRAINT FK_C65C611CB2DABD03');
        $this->addSql('DROP TABLE planning');
        $this->addSql('DROP TABLE planning_ligne');
    }
}
