<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260203132218 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bon_de_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_bc VARCHAR(50) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, forfait VARCHAR(100) DEFAULT NULL, client_id INT NOT NULL, fiche_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C3802E419EB6921 ON bon_de_commande (client_id)');
        $this->addSql('CREATE INDEX IDX_2C3802E4DF522508 ON bon_de_commande (fiche_id)');
        $this->addSql('ALTER TABLE bon_de_commande ADD CONSTRAINT FK_2C3802E419EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_de_commande ADD CONSTRAINT FK_2C3802E4DF522508 FOREIGN KEY (fiche_id) REFERENCES fiche_dechargement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bon_de_commande DROP CONSTRAINT FK_2C3802E419EB6921');
        $this->addSql('ALTER TABLE bon_de_commande DROP CONSTRAINT FK_2C3802E4DF522508');
        $this->addSql('DROP TABLE bon_de_commande');
    }
}
