<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260211085809 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bon_travail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(50) NOT NULL, delai_client DATE DEFAULT NULL, exigence_particuliere TEXT DEFAULT NULL, reprise_usinage VARCHAR(255) DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, bon_commande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5691DF71B4B54061 ON bon_travail (bon_commande_id)');
        $this->addSql('ALTER TABLE bon_travail ADD CONSTRAINT FK_5691DF71B4B54061 FOREIGN KEY (bon_commande_id) REFERENCES bon_de_commande (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bon_travail DROP CONSTRAINT FK_5691DF71B4B54061');
        $this->addSql('DROP TABLE bon_travail');
    }
}
