<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260128134320 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fiche_dechargement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, observations TEXT DEFAULT NULL, total_paquets INT NOT NULL, cariste_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F82A59797605FF4A ON fiche_dechargement (cariste_id)');
        $this->addSql('CREATE INDEX IDX_F82A597919EB6921 ON fiche_dechargement (client_id)');
        $this->addSql('CREATE TABLE ligne_dechargement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nb_paquets INT NOT NULL, emplacement VARCHAR(255) NOT NULL, fiche_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1C640483DF522508 ON ligne_dechargement (fiche_id)');
        $this->addSql('CREATE TABLE photo_dechargement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_fichier VARCHAR(255) NOT NULL, fiche_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2BD14D5FDF522508 ON photo_dechargement (fiche_id)');
        $this->addSql('ALTER TABLE fiche_dechargement ADD CONSTRAINT FK_F82A59797605FF4A FOREIGN KEY (cariste_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fiche_dechargement ADD CONSTRAINT FK_F82A597919EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_dechargement ADD CONSTRAINT FK_1C640483DF522508 FOREIGN KEY (fiche_id) REFERENCES fiche_dechargement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_dechargement ADD CONSTRAINT FK_2BD14D5FDF522508 FOREIGN KEY (fiche_id) REFERENCES fiche_dechargement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fiche_dechargement DROP CONSTRAINT FK_F82A59797605FF4A');
        $this->addSql('ALTER TABLE fiche_dechargement DROP CONSTRAINT FK_F82A597919EB6921');
        $this->addSql('ALTER TABLE ligne_dechargement DROP CONSTRAINT FK_1C640483DF522508');
        $this->addSql('ALTER TABLE photo_dechargement DROP CONSTRAINT FK_2BD14D5FDF522508');
        $this->addSql('DROP TABLE fiche_dechargement');
        $this->addSql('DROP TABLE ligne_dechargement');
        $this->addSql('DROP TABLE photo_dechargement');
    }
}
