<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260721070342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document_bon_livraison (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_fichier VARCHAR(255) NOT NULL, bon_livraison_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_160A952FD8D16068 ON document_bon_livraison (bon_livraison_id)');
        $this->addSql('ALTER TABLE document_bon_livraison ADD CONSTRAINT FK_160A952FD8D16068 FOREIGN KEY (bon_livraison_id) REFERENCES bon_livraison (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document_bon_livraison DROP CONSTRAINT FK_160A952FD8D16068');
        $this->addSql('DROP TABLE document_bon_livraison');
    }
}
