<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260728064513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE emplacement_apres_production (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE ligne_dechargement ADD emplacement_apres_production_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ligne_dechargement ADD CONSTRAINT FK_1C640483D5ABF007 FOREIGN KEY (emplacement_apres_production_id) REFERENCES emplacement_apres_production (id)');
        $this->addSql('CREATE INDEX IDX_1C640483D5ABF007 ON ligne_dechargement (emplacement_apres_production_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE emplacement_apres_production');
        $this->addSql('ALTER TABLE ligne_dechargement DROP CONSTRAINT FK_1C640483D5ABF007');
        $this->addSql('DROP INDEX IDX_1C640483D5ABF007');
        $this->addSql('ALTER TABLE ligne_dechargement DROP emplacement_apres_production_id');
    }
}
