<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260204100002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE photo_bon_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_fichier VARCHAR(255) NOT NULL, bon_de_commande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9AF69C65D29E677C ON photo_bon_commande (bon_de_commande_id)');
        $this->addSql('ALTER TABLE photo_bon_commande ADD CONSTRAINT FK_9AF69C65D29E677C FOREIGN KEY (bon_de_commande_id) REFERENCES bon_de_commande (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE photo_bon_commande DROP CONSTRAINT FK_9AF69C65D29E677C');
        $this->addSql('DROP TABLE photo_bon_commande');
    }
}
