<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260130141510 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE emplacement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE ligne_dechargement ADD emplacement_id INT NOT NULL');
        $this->addSql('ALTER TABLE ligne_dechargement DROP emplacement');
        $this->addSql('ALTER TABLE ligne_dechargement ADD CONSTRAINT FK_1C640483C4598A51 FOREIGN KEY (emplacement_id) REFERENCES emplacement (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_1C640483C4598A51 ON ligne_dechargement (emplacement_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE emplacement');
        $this->addSql('ALTER TABLE ligne_dechargement DROP CONSTRAINT FK_1C640483C4598A51');
        $this->addSql('DROP INDEX IDX_1C640483C4598A51');
        $this->addSql('ALTER TABLE ligne_dechargement ADD emplacement VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE ligne_dechargement DROP emplacement_id');
    }
}
