<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260730115529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dechargement_urgence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(255) DEFAULT NULL, client_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F7B5053D19EB6921 ON dechargement_urgence (client_id)');
        $this->addSql('CREATE TABLE ligne_dechargement_urgence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nb_palettes INT DEFAULT NULL, nom_produit VARCHAR(255) DEFAULT NULL, poids VARCHAR(255) DEFAULT NULL, bac VARCHAR(255) DEFAULT NULL, dechargement_urgence_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_18BB1B558C8E0042 ON ligne_dechargement_urgence (dechargement_urgence_id)');
        $this->addSql('CREATE TABLE photo_urgence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_fichier VARCHAR(255) NOT NULL, dechargement_urgence_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_469D7C408C8E0042 ON photo_urgence (dechargement_urgence_id)');
        $this->addSql('ALTER TABLE dechargement_urgence ADD CONSTRAINT FK_F7B5053D19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE ligne_dechargement_urgence ADD CONSTRAINT FK_18BB1B558C8E0042 FOREIGN KEY (dechargement_urgence_id) REFERENCES dechargement_urgence (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_urgence ADD CONSTRAINT FK_469D7C408C8E0042 FOREIGN KEY (dechargement_urgence_id) REFERENCES dechargement_urgence (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dechargement_urgence DROP CONSTRAINT FK_F7B5053D19EB6921');
        $this->addSql('ALTER TABLE ligne_dechargement_urgence DROP CONSTRAINT FK_18BB1B558C8E0042');
        $this->addSql('ALTER TABLE photo_urgence DROP CONSTRAINT FK_469D7C408C8E0042');
        $this->addSql('DROP TABLE dechargement_urgence');
        $this->addSql('DROP TABLE ligne_dechargement_urgence');
        $this->addSql('DROP TABLE photo_urgence');
    }
}
