<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325130040 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bon_livraison (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(50) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_enlevement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, immatriculation VARCHAR(50) DEFAULT NULL, transporteur VARCHAR(150) DEFAULT NULL, chauffeur VARCHAR(150) DEFAULT NULL, signature TEXT DEFAULT NULL, bon_travail_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31A531A4F55AE19E ON bon_livraison (numero)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31A531A4B2DABD03 ON bon_livraison (bon_travail_id)');
        $this->addSql('ALTER TABLE bon_livraison ADD CONSTRAINT FK_31A531A4B2DABD03 FOREIGN KEY (bon_travail_id) REFERENCES bon_travail (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bon_livraison DROP CONSTRAINT FK_31A531A4B2DABD03');
        $this->addSql('DROP TABLE bon_livraison');
    }
}
